export const codesNames = {
	ad: "Andorra",
	ae: "United Arab Emirates",
	af: "Afghanistan",
	ag: "Antigua and Barbuda",
	ai: "Anguilla",
	aq: "Antarctica",
	al: "Albania",
	am: "Armenia",
	ao: "Angola",
	ar: "Argentina",
	as: "American Samoa",
	at: "Austria",
	au: "Australia",
	aw: "Aruba",
	fiax: "Åland Islands (Finland)",
	az: "Azerbaijan",
	ba: "Bosnia and Herzegovina",
	bb: "Barbados",
	bd: "Bangladesh",
	be: "Belgium",
	bf: "Burkina Faso",
	bg: "Bulgaria",
	bh: "Bahrain",
	bi: "Burundi",
	bj: "Benin",
	bl: "Saint Barthelemy",
	bm: "Bermuda",
	bn: "Brunei",
	bo: "Bolivia",
	br: "Brazil",
	bs: "Bahamas",
	bt: "Bhutan",
	bv: "Bouvet Island",
	bw: "Botswana",
	by: "Belarus",
	bz: "Belize",
	ca: "Canada",
	aucc: "Cocos Islands (Australia)",
	cg: "Congo",
	cd: "Democratic Republic of the Congo",
	cf: "Central African Republic",
	ch: "Switzerland",
	ci: "Ivory Coast",
	ck: "Cook Islands",
	cl: "Chile",
	cm: "Cameroon",
	cn: "China",
	co: "Colombia",
	cr: "Costa Rica",
	cu: "Cuba",
	cv: "Cape Verde",
	nlcw: "Curaçao (Netherlands)",
	aucx: "Christmas Island (Australia)",
	cy: "Cyprus",
	cz: "Czech Republic",
	de: "Germany",
	dj: "Djibouti",
	dk: "Denmark",
	dkfo: "Faroe Islands (Denmark)",
	dm: "Dominica",
	do: "Dominican Republic",
	dz: "Algeria",
	ec: "Ecuador",
	ee: "Estonia",
	eg: "Egypt",
	eh: "Western Sahara",
	er: "Eritrea",
	es: "Spain",
	et: "Ethiopia",
	eu: "Europe",
	fi: "Finland",
	fj: "Fiji",
	fm: "Micronesia",
	fr: "France",
	frpm: "Saint Pierre and Miquelon (France)",
	frgf: "French Guiana (France)",
	ga: "Gabon",
	uk: "United Kingdom",
	ukfk: "Falkland Islands (UK)",
	gd: "Grenada",
	ge: "Georgia",
	gg: "Guernsey (UK)",
	gh: "Ghana",
	ukgi: "Gibraltar (UK)",
	gl: "Greenland",
	gm: "Gambia",
	gn: "Guinea",
	gp: "Guadeloupe",
	gq: "Equatorial Guinea",
	gr: "Greece",
	ukgs: "South Georgia and the South Sandwich Islands (UK)",
	gt: "Guatemala",
	gu: "Guam",
	gw: "Guinea-Bissau",
	gy: "Guyana",
	hk: "Hong Kong",
	auhm: "Heard Island and McDonald Islands (Australia)",
	hn: "Honduras",
	hr: "Croatia",
	ht: "Haiti",
	hu: "Hungary",
	id: "Indonesia",
	ie: "Ireland",
	il: "Israel",
	ukim: "Isle of Man (UK)",
	in: "India",
	io: "British Indian Ocean Territory",
	iq: "Iraq",
	ir: "Iran",
	is: "Iceland",
	it: "Italy",
	ukje: "Jersey (UK)",
	jm: "Jamaica",
	jo: "Jordan",
	jp: "Japan",
	ke: "Kenya",
	kg: "Kyrgyzstan",
	kh: "Cambodia",
	ki: "Kiribati",
	km: "Comoros",
	kn: "Saint Kitts and Nevis",
	kp: "North Korea",
	kr: "South Korea",
	kw: "Kuwait",
	ky: "Cayman Islands",
	kz: "Kazakhstan",
	la: "Laos",
	lb: "Lebanon",
	lc: "Saint Lucia",
	li: "Liechtenstein",
	lk: "Sri Lanka",
	lr: "Liberia",
	ls: "Lesotho",
	lt: "Lithuania",
	lu: "Luxembourg",
	lv: "Latvia",
	ly: "Libya",
	ma: "Morocco",
	mc: "Monaco",
	md: "Moldova",
	me: "Montenegro",
	mf: "Saint Martin",
	mg: "Madagascar",
	mh: "Marshall Islands",
	mk: "North Macedonia",
	ml: "Mali",
	mm: "Myanmar",
	mn: "Mongolia",
	mo: "Macau",
	usmp: "Northern Mariana Islands (US)",
	mq: "Martinique",
	mr: "Mauritania",
	ukms: "Montserrat (UK)",
	mt: "Malta",
	mu: "Mauritius",
	mv: "Maldives",
	mw: "Malawi",
	mx: "Mexico",
	my: "Malaysia",
	mz: "Mozambique",
	na: "Namibia",
	nc: "New Caledonia",
	ne: "Niger",
	nf: "Norfolk Island",
	ng: "Nigeria",
	ni: "Nicaragua",
	nl: "Netherlands",
	nlcw: "Curaçao (Netherlands)",
	no: "Norway",
	np: "Nepal",
	nr: "Nauru",
	nu: "Niue",
	nz: "New Zealand",
	om: "Oman",
	pa: "Panama",
	pe: "Peru",
	pf: "French Polynesia",
	pg: "Papua New Guinea",
	ph: "Philippines",
	pk: "Pakistan",
	pl: "Poland",
	pn: "Pitcairn",
	uspr: "Puerto Rico",
	ps: "Palestine",
	pt: "Portugal",
	pw: "Palau",
	py: "Paraguay",
	qa: "Qatar",
	re: "Reunion",
	ro: "Romania",
	rs: "Serbia",
	ru: "Russia",
	rw: "Rwanda",
	sa: "Saudi Arabia",
	sb: "Solomon Islands",
	sc: "Seychelles",
	sd: "Sudan",
	se: "Sweden",
	sg: "Singapore",
	uksh: "Saint Helena, Ascension and Tristan da Cunha",
	si: "Slovenia",
	nosj: "Svalbard (Norway)",
	sk: "Slovakia",
	sl: "Sierra Leone",
	sm: "San Marino",
	sn: "Senegal",
	so: "Somalia",
	sr: "Suriname",
	ss: "South Sudan",
	st: "Sao Tome and Principe",
	sv: "El Salvador",
	sx: "Sint Maarten",
	sy: "Syria",
	sz: "eSwatini",
	tb: "Tibet",
	tc: "Turks and Caicos Islands",
	td: "Chad",
	tf: "French Southern Territories",
	tg: "Togo",
	th: "Thailand",
	tj: "Tajikistan",
	tk: "Tokelau",
	tl: "Timor-Leste",
	tm: "Turkmenistan",
	tn: "Tunisia",
	to: "Tonga",
	tr: "Turkey",
	tt: "Trinidad and Tobago",
	tv: "Tuvalu",
	tw: "Taiwan",
	tz: "Tanzania",
	ua: "Ukraine",
	ug: "Uganda",
	us: "United States",
	uy: "Uruguay",
	uz: "Uzbekistan",
	va: "Vatican",
	vc: "Saint Vincent and the Grenadines",
	ve: "Venezuela",
	vg: "British Virgin Islands",
	vi: "US Virgin Islands",
	vn: "Viet Nam",
	vu: "Vanuatu",
	wf: "Wallis and Futuna",
	ws: "Samoa",
	ye: "Yemen",
	yt: "Mayotte",
	za: "South Africa",
	zm: "Zambia",
	zw: "Zimbabwe",
	xk: "Kosovo",
};
